### PR TITLE
Update ffmpeg to major version 6

### PR DESCRIPTION
**Pull request by Martchus**

### CODE REVIEW

**Comment by Martchus** [comment]
I've tested this with a local container build and it seems to work. By the way, I'm going to use this to encode openQA videos with SVT-1 under Leap which we use for our openQA workers (https://github.com/os-autoinst/os-autoinst/pull/2327).

**Comment by tamara-schmitz** [comment]
Really cool. Sadly this is not OBS friendly due to packman and has to be build externally. After all OBS does not allow external repos or downloads.

But perhaps we can make an OBS friendly version by removing all the patented codecs and getting rid of Pacman?

**Comment by Martchus** [comment]
> But perhaps we can make an OBS friendly version by removing all the patented codecs and getting rid of Pacman?

I suppose that's what I will do when we really wanted to use this broadly in production. This shouldn't be hard to setup. For now your repository is useful enough.

**Comment by tamara-schmitz** [comment]
I'm on it #2.

**Pull request merged**
